/**
 * CSE JnU EduPortal - Canonical Error Codes
 * Defined in docs/api/error_handling.md
 */

export const ErrorCode = {
  // Authentication & Session
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',

  // Authorization & Permissions
  FORBIDDEN_RESOURCE: 'FORBIDDEN_RESOURCE',

  // Validation & Input
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  BAD_REQUEST: 'BAD_REQUEST',

  // Resource Lookups
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  // Domain Specific State Invariants
  INVALID_VERIFICATION_CODE: 'INVALID_VERIFICATION_CODE',
  DUPLICATE_ATTENDANCE: 'DUPLICATE_ATTENDANCE',
  SESSION_ALREADY_ACTIVE: 'SESSION_ALREADY_ACTIVE',
  SLOT_NOT_AVAILABLE: 'SLOT_NOT_AVAILABLE',
  DUPLICATE_BOOKING_REQUEST: 'DUPLICATE_BOOKING_REQUEST',
  CR_DATE_LOCKED: 'CR_DATE_LOCKED',
  SCHEDULE_COLLISION: 'SCHEDULE_COLLISION',
  PENDING_SIGNUP_EXISTS: 'PENDING_SIGNUP_EXISTS',
  PENDING_SEMESTER_EXISTS: 'PENDING_SEMESTER_EXISTS',

  // Media & Rate Limiting
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // System & Database
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
