// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4jae-WiPeCGo6zYQ1b6IQDKTyHZYgZ6Q',
    appId: '1:685171866402:web:9c97e6831a32a9642d037b',
    messagingSenderId: '685171866402',
    projectId: 'sajib-73b14',
    authDomain: 'sajib-73b14.firebaseapp.com',
    storageBucket: 'sajib-73b14.firebasestorage.app',
    measurementId: 'G-87X20PFQF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLIjwgv-TBkSghNH7wwBXq72G_gk-dvj0',
    appId: '1:685171866402:android:2bf560d9bc8b3d582d037b',
    messagingSenderId: '685171866402',
    projectId: 'sajib-73b14',
    storageBucket: 'sajib-73b14.firebasestorage.app',
  );
}
